### ISSUE TITLE
Vectors? Colors?

### ISSUE THREAD

**Issue by p4stoboy** [andithemudkip/p5-node#2]
I'm getting p5.Vector is not a constructor / color() is not a function etc.

Is this package supposed to have all the 2d functionality of the original? Or just text?

Edit - this is all outside the sketch function. Passing p into the sketch function and trying p.Vector() in there gives me no joy either.

**Comment by andithemudkip** [comment]
*first of all, a disclaimer, this library is a glued-together abomination lmao*
color should be working with p.color inside the sketch function;
looks like I completely forgot about vectors, I just pushed an update that added them to the p object as well
I should consider rewriting it at some point because my implementation is horrendous
